### ISSUE TITLE
typo platfolm

### ISSUE THREAD

**Issue by miso-develop** [line-developer-community/techbookfest7#7]
タイトルや本文にPlatfolmというタイポが散見します！

**Comment by miso-develop** [comment]
ちなみに本タイトルがLINE API HANDBOOKなので、LINE Platform→LINE APIだと違和感ある？

**Comment by miso-develop** [comment]
* サーバーの表記揺れ
* github -> GitHub
* Nodejs -> Node.js

もありました

**Comment by mochan-tk** [comment]
失礼しました。txtlint対応いたします。

**Comment by mochan-tk** [comment]
txtlint対応しました。LINE Platform→LINE APIの件は。。別で相談させてください。
