### ISSUE TITLE
表の横幅について

### ISSUE THREAD

**Issue by miso-develop** [line-developer-community/techbookfest7#9]
表の横幅はヘッダーの下線の範囲に収まるように注意してください。
紙媒体に印刷時、糊付け部のマージンが確保され、その分全体的に位置が横にずれます。
ヘッダー下線の幅を超えると糊付けマージン部に入って読めなくなってしまいます。

全体を流し見したところAssigneesの3名の表が幅オーバーしていたので、該当箇所の修正をお願いします！

参考までに↓のファイルが紙媒体印刷用に糊付け部の確保と本文の左右ずらしを行ったPDFになります。
[紙媒体印刷用PDF](https://github.com/line-developer-community/techbookfest7/files/3547055/techbookfest7_compressed.pdf)

**Comment by miso-develop** [comment]
参考までに、こんな感じになります。

奇数ページ（加川さんの章）
![image](https://user-images.githubusercontent.com/22117028/63788956-53526500-c931-11e9-81e5-a21af7501818.png)

偶数ページ（ひらりんさんの章）
![unknown](https://user-images.githubusercontent.com/22117028/63789023-7b41c880-c931-11e9-84ab-f06a37fabc71.png)

**Comment by gaomar** [comment]
がおまる分該当箇所を表から画像に変更しました。

**Comment by sumihiro3** [comment]
表を画像に変更しました。

**Comment by himanago** [comment]
画像にしました

**Comment by miso-develop** [comment]
ご対応ありがとうございました！
